require_relative 'db_comment_provider'
require_relative 'video_view_provider'
require_relative 'video_rating_provider'
require_relative 'quiz_score_provider'
require_relative 'json_module_provider'
require_relative 'user_role_provider'
require_relative 'user_provider'
